{
 "title": "Load Shed API Main",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(http_requests_total{job=\"load-shed-api\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "p95 upstream latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(upstream_request_duration_seconds_bucket{job=\"load-shed-api\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory RSS (bytes) per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by (pod) (\r\n  process_resident_memory_bytes{job=\"load-shed-api\", pod=~\"$pod\"}\r\n)"
    }
   ]
  },
  {
   "title": "Upstream requests by result",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(result) (rate(upstream_requests_total{job=\"load-shed-api\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/client p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (pod, le) (rate(http_request_duration_seconds_bucket{job=\"load-shed-api\",path=\"/client\"}[$__rate_interval]))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Circuit breaker state over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by(pod) (circuit_breaker_state{job=\"load-shed-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage (cores) per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(process_cpu_seconds_total{job=\"load-shed-api\", pod=~\"$pod\"}[1m])\r\n)"
    }
   ]
  },
  {
   "title": "/client request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(http_requests_total{job=\"load-shed-api\",path=\"/client\"}[$__rate_interval]))\r\n"
    }
   ]
  },
  {
   "title": "Load shed rate (429) - /client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"load-shed-api\", path=\"/client\", status=\"429\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}